ktor:
  application:
    modules:
      - com.tadak.ApplicationKt.module

  deployment:
    port: 8080

  jwt:
    secret: "tadaktadaktadaktadaktadaktadaktadakdevtadaktadaktadaktadaktadaktadaktadaktadak"
    issuer: "tadak-auth-gateway"

  datasource:
    jdbcUrl: "jdbc:mysql://k12a703.p.ssafy.io:3310/tadakuser?serverTimezone=Asia/Seoul"
    driver: "com.mysql.cj.jdbc.Driver"
    username: "dadada"
    password: "dadada!"
    maximumPoolSize: "10"
    transactionIsolation: "TRANSACTION_REPEATABLE_READ"

  proxy:
    spring: "http://td-spring-dev"
    fastapi: "http://td-fastapi-dev"

  minio:
    url: "https://minio.tadak.kr"
    accessKey: "dadada"
    secretKey: "dadada!!"
    bucket: "image"
    baseUrl: "https://minio.tadak.kr"

oauth:
  kakao:
    client-id: "1a3c84e2a5568d5e18f196334f194d36"
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-uri: "https://kapi.kakao.com/v2/user/me"
    dev-redirect-uri: "https://dev.tadak.kr/auth/kakao/callback"
    local-redirect-uri: "http://localhost:5173/auth/kako/callback"
    deploy-redirect-uri: "https://tadak.kr/auth/kakao/callback"