ktor:
  application:
    modules:
      - com.tadak.ApplicationKt.module

  deployment:
    port: 8080

  jwt:
    secret: "tadaktadaktadaktadaktadaktadaktadakdevtadaktadaktadaktadaktadaktadaktadaktadak"
    issuer: "tadak-auth-gateway"

  datasource:
    jdbcUrl: "jdbc:mysql://k12a703.p.ssafy.io:3310/tadakuser?serverTimezone=Asia/Seoul"
    driver: "com.mysql.cj.jdbc.Driver"
    username: "dadada"
    password: "dadada!"
    maximumPoolSize: "10"
    transactionIsolation: "TRANSACTION_REPEATABLE_READ"

  proxy:
    spring: "http://td-spring-dev"
    fastapi: "http://td-fastapi-dev"